version: '3'
services:
  app:
    image: 'nut-upsd'
    restart: unless-stopped
    hostname: Nut
    ports:
      - '3493:3493'
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - /docker/nut/config:/etc/nut
